"""initial schema: users, employees, seats, projects, allocations, audit

Revision ID: 382bc0c49159
Revises: 
Create Date: 2026-07-08 15:06:37.479379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382bc0c49159'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_code', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('designation', sa.String(length=80), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_LEAVE', 'EXITED', name='employee_status', native_enum=False, length=32), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('current_seat_id', sa.Integer(), nullable=True),
    sa.Column('current_project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_project_id'], ['projects.id'], name=op.f('fk_employees_current_project_id_projects'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['current_seat_id'], ['seats.id'], name=op.f('fk_employees_current_seat_id_seats'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name=op.f('fk_employees_manager_id_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_index(op.f('ix_employees_current_project_id'), 'employees', ['current_project_id'], unique=False)
    op.create_index(op.f('ix_employees_current_seat_id'), 'employees', ['current_seat_id'], unique=False)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index('ix_employees_dept_status', 'employees', ['department', 'status'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_emp_code'), 'employees', ['emp_code'], unique=True)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('client', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', name='project_status', native_enum=False, length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('required_seats', sa.Integer(), nullable=False),
    sa.Column('pm_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pm_id'], ['employees.id'], name=op.f('fk_projects_pm_id_employees'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_index(op.f('ix_projects_pm_id'), 'projects', ['pm_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_code', sa.String(length=32), nullable=False),
    sa.Column('building', sa.String(length=16), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=16), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'BLOCKED', name='seat_status', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats'))
    )
    op.create_index('ix_seats_building_floor', 'seats', ['building', 'floor'], unique=False)
    op.create_index(op.f('ix_seats_seat_code'), 'seats', ['seat_code'], unique=True)
    op.create_index(op.f('ix_seats_status'), 'seats', ['status'], unique=False)
    op.create_index('ix_seats_status_floor', 'seats', ['status', 'floor'], unique=False)
    op.create_table('project_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('allocation_pct', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocation_pct BETWEEN 0 AND 100', name=op.f('ck_project_assignments_allocation_range')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_project_assignments_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_assignments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_assignments')),
    sa.UniqueConstraint('employee_id', 'project_id', 'start_date', name='uq_assignment_emp_proj_start')
    )
    op.create_index('ix_pa_active', 'project_assignments', ['employee_id', 'end_date'], unique=False)
    op.create_index(op.f('ix_project_assignments_employee_id'), 'project_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_project_assignments_project_id'), 'project_assignments', ['project_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'HR', 'PM', 'EMPLOYEE', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_users_employee_id_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_users_employee_id'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_query_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_query_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_query_log'))
    )
    op.create_index(op.f('ix_ai_query_log_at'), 'ai_query_log', ['at'], unique=False)
    op.create_index(op.f('ix_ai_query_log_user_id'), 'ai_query_log', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('ALLOCATE', 'RELEASE', 'TRANSFER', 'BLOCK', 'RESERVE', 'ASSIGN_PROJECT', 'UNASSIGN_PROJECT', 'CREATE_EMPLOYEE', 'UPDATE_EMPLOYEE', 'CHANGE_ROLE', name='audit_action', native_enum=False, length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('seat_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allocated_by_id', sa.Integer(), nullable=True),
    sa.Column('released_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocated_by_id'], ['users.id'], name=op.f('fk_seat_allocations_allocated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_seat_allocations_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], name=op.f('fk_seat_allocations_released_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_seat_allocations_seat_id_seats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_allocations'))
    )
    op.create_index('ix_alloc_emp_active', 'seat_allocations', ['employee_id', 'released_at'], unique=False)
    op.create_index('ix_alloc_seat_active', 'seat_allocations', ['seat_id', 'released_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alloc_seat_active', table_name='seat_allocations')
    op.drop_index('ix_alloc_emp_active', table_name='seat_allocations')
    op.drop_table('seat_allocations')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_ai_query_log_user_id'), table_name='ai_query_log')
    op.drop_index(op.f('ix_ai_query_log_at'), table_name='ai_query_log')
    op.drop_table('ai_query_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_project_assignments_project_id'), table_name='project_assignments')
    op.drop_index(op.f('ix_project_assignments_employee_id'), table_name='project_assignments')
    op.drop_index('ix_pa_active', table_name='project_assignments')
    op.drop_table('project_assignments')
    op.drop_index('ix_seats_status_floor', table_name='seats')
    op.drop_index(op.f('ix_seats_status'), table_name='seats')
    op.drop_index(op.f('ix_seats_seat_code'), table_name='seats')
    op.drop_index('ix_seats_building_floor', table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_pm_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_emp_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index('ix_employees_dept_status', table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index(op.f('ix_employees_current_seat_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_current_project_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
